// WRF Domain Wizard - native manual rectangle drawing + interactive resizing
const map=L.map('map',{preferCanvas:true}).setView([20,78],5);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:19}).addTo(map);
const drawnItems=new L.FeatureGroup().addTo(map),domains=[];
const colors=['#dc3545','#0d6efd','#198754','#6f42c1','#fd7e14','#20c997','#d63384','#6610f2','#1982c4','#495057'];
const countEl=document.getElementById('domainCount'),ratioTable=document.getElementById('ratioTable');
let drawingActive=false,drawingPointerId=null,startLatLng=null,preview=null;
let resizeHandles=[],resizing=false,resizeDomainIndex=null,resizeCorner=null;
function pad(i){return String(i+1).padStart(2,'0');}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function emitChanged(){window.dispatchEvent(new CustomEvent('wrf-domains-changed'));}
function buildRatioTable(){const n=Number(countEl.value),old=[...document.querySelectorAll('.ratio-input')].map(x=>x.value);if(n<2){ratioTable.innerHTML='<div class="small text-muted">Single domain: no nesting ratio required.</div>';return;}ratioTable.innerHTML='<div class="small fw-semibold mb-1">Parent → child nesting ratios</div>'+Array.from({length:n-1},(_,k)=>{const r=old[k]||3;return `<div class="row g-2 align-items-center mb-1"><div class="col-7"><span class="small">d${pad(k)} → d${pad(k+1)}</span></div><div class="col-5"><div class="input-group input-group-sm"><input class="form-control ratio-input" data-child="${k+1}" type="number" min="2" max="10" step="1" value="${r}"><span class="input-group-text">:1</span></div></div></div>`}).join('');document.querySelectorAll('.ratio-input').forEach(x=>x.addEventListener('input',updateOutputFromDomains));}
function ratios(){const r=Array(Number(countEl.value)).fill(1);document.querySelectorAll('.ratio-input').forEach(x=>r[Number(x.dataset.child)]=Number(x.value));return r;}
function settings(){if(!domains.length)throw new Error('Draw d01 first.');const projection=document.getElementById('projectionInput').value,b=domains[0].getBounds(),auto=document.getElementById('autoCenterInput').checked,refLat=auto?b.getCenter().lat:Number(document.getElementById('refLatInput').value),refLon=auto?b.getCenter().lng:Number(document.getElementById('refLonInput').value);if(!Number.isFinite(refLat)||refLat<=-90||refLat>=90||!Number.isFinite(refLon)||refLon<-180||refLon>180)throw new Error('Reference latitude/longitude must be valid.');const s={projection,refLat,refLon};if(projection==='lambert'){s.truelat1=Number(document.getElementById('trueLat1Input').value);s.truelat2=Number(document.getElementById('trueLat2Input').value);}if(projection==='polar'){s.polarLat=Number(document.getElementById('polarLatInput').value);s.hemisphere=document.getElementById('polarHemisphere').value;}return s;}
function spacing(){const p=document.getElementById('projectionInput').value,dx=Number(document.getElementById('dxInput').value),dy=Number(document.getElementById('dyInput').value);if(!(dx>0&&dy>0))throw new Error('d01 dx/dy must be positive.');if(p!=='lat-lon'&&(dx<100||dy<100))throw new Error('Projected-grid dx/dy must be at least 100 m.');return{dx,dy};}
function wpsSettings(){const start=document.getElementById('startDateInput').value.trim(),end=document.getElementById('endDateInput').value.trim(),interval=Number(document.getElementById('intervalInput').value),path=document.getElementById('geogPathInput').value.trim(),re=/^\d{4}-\d{2}-\d{2}_\d{2}:\d{2}:\d{2}$/;if(!re.test(start)||!re.test(end))throw new Error('Dates must use YYYY-MM-DD_HH:MM:SS format.');if(start>=end)throw new Error('end_date must be later than start_date.');if(!Number.isInteger(interval)||interval<=0)throw new Error('interval_seconds must be a positive integer.');if(!path)throw new Error('geog_data_path cannot be empty.');return{startDate:start,endDate:end,intervalSeconds:interval,geogPath:path};}
function addDomain(layer,index){layer.options.domainIndex=index;layer.setStyle({color:colors[index],weight:3,fillOpacity:.08});layer.bindTooltip(`d${pad(index)}`,{sticky:true});drawnItems.addLayer(layer);domains.push(layer);}
function cancelDrawing(){drawingActive=false;drawingPointerId=null;startLatLng=null;if(preview){map.removeLayer(preview);preview=null;}map.getContainer().style.cursor='';map.dragging.enable();}
function clearResizeHandles(){resizeHandles.forEach(h=>drawnItems.removeLayer(h));resizeHandles=[];resizing=false;resizeDomainIndex=null;resizeCorner=null;}
function makeResizeHandles(){clearResizeHandles();if(!domains.length)return;domains.forEach((layer,index)=>{const b=layer.getBounds(),corners=[['nw',b.getNorthWest()],['ne',b.getNorthEast()],['se',b.getSouthEast()],['sw',b.getSouthWest()]];corners.forEach(([corner,ll])=>{const h=L.marker(ll,{draggable:true,autoPan:false,zIndexOffset:1000,icon:L.divIcon({className:'wrf-resize-handle',html:'',iconSize:[12,12],iconAnchor:[6,6]})});h._wrfDomainIndex=index;h._wrfCorner=corner;h.on('dragstart',()=>{if(drawingActive)return;resizing=true;resizeDomainIndex=index;resizeCorner=corner;map.dragging.disable();});h.on('drag',e=>{if(!resizing||resizeDomainIndex!==index||resizeCorner!==corner)return;applyResize(index,corner,e.target.getLatLng(),false);});h.on('dragend',e=>{if(resizeDomainIndex===index)applyResize(index,corner,e.target.getLatLng(),true);resizing=false;resizeDomainIndex=null;resizeCorner=null;map.dragging.enable();});h.addTo(drawnItems);resizeHandles.push(h);});});}
function boundsForResize(old,corner,p){let north=old.getNorth(),south=old.getSouth(),east=old.getEast(),west=old.getWest();if(corner==='nw'){north=p.lat;west=p.lng;}if(corner==='ne'){north=p.lat;east=p.lng;}if(corner==='se'){south=p.lat;east=p.lng;}if(corner==='sw'){south=p.lat;west=p.lng;}if(north<south)[north,south]=[south,north];if(east<west)[east,west]=[west,east];return L.latLngBounds([south,west],[north,east]);}
function applyResize(index,corner,p,finalize){if(!p)return false;const layer=domains[index],old=layer.getBounds(),b=boundsForResize(old,corner,p);if(b.getNorth()-b.getSouth()<0.05||b.getEast()-b.getWest()<0.05){if(finalize){showError(`d${pad(index)} is too small. Resize it to a larger area.`);refreshResizeHandles();}return false;}if(index>0&&!domains[index-1].getBounds().contains(b)){if(finalize)showError(`d${pad(index)} must remain fully inside d${pad(index-1)}.`);return false;}if(index<domains.length-1){for(let j=index+1;j<domains.length;j++){if(!b.contains(domains[j].getBounds())){if(finalize)showError(`d${pad(index)} cannot be resized because d${pad(j)} would fall outside its parent.`);return false;}}}layer.setBounds(b);updateResizeHandlePositions();updateOutputFromDomains();emitChanged();if(finalize)showMessage(`d${pad(index)} resized. Grid dimensions and nesting diagnostics have been updated.`);return true;}
function updateResizeHandlePositions(){resizeHandles.forEach(h=>{const i=h._wrfDomainIndex,b=domains[i].getBounds(),pts={nw:b.getNorthWest(),ne:b.getNorthEast(),se:b.getSouthEast(),sw:b.getSouthWest()};h.setLatLng(pts[h._wrfCorner]);});}
function refreshResizeHandles(){makeResizeHandles();}
function clearDomains(show=true){cancelDrawing();clearResizeHandles();drawnItems.clearLayers();domains.length=0;if(show)showMessage('All domains cleared.');else updateOutputFromDomains();emitChanged();}
function startDrawing(){clearDomains(false);drawingActive=true;showMessage('d01 drawing is active — click and drag directly on the map.');map.getContainer().style.cursor='crosshair';map.dragging.disable();}
function pointerDown(e){if(!drawingActive||drawingPointerId!==null)return;const target=e.originalEvent?.target;if(target&&target.closest&&target.closest('.leaflet-control'))return;e.originalEvent.preventDefault();drawingPointerId=e.originalEvent.pointerId??1;startLatLng=e.latlng;preview=L.rectangle([startLatLng,startLatLng],{color:'#000',weight:2,dashArray:'6 4',fillOpacity:.05,interactive:false}).addTo(map);}
function pointerMove(e){if(!drawingActive||drawingPointerId===null||!preview)return;e.originalEvent?.preventDefault?.();preview.setBounds(L.latLngBounds(startLatLng,e.latlng));}
function pointerUp(e){if(!drawingActive||drawingPointerId===null)return;e.originalEvent?.preventDefault?.();drawingPointerId=null;const end=e.latlng,b=L.latLngBounds(startLatLng,end);startLatLng=null;if(preview){map.removeLayer(preview);preview=null;}if(Math.abs(b.getNorth()-b.getSouth())<0.05||Math.abs(b.getEast()-b.getWest())<0.05){showError('Domain is too small. Click and drag a larger rectangle.');return;}const i=domains.length,n=Number(countEl.value);if(i>0&&!domains[i-1].getBounds().contains(b)){showError(`d${pad(i)} must be fully contained inside d${pad(i-1)}. Draw it again.`);return;}addDomain(L.rectangle(b),i);updateOutputFromDomains();emitChanged();makeResizeHandles();if(domains.length>=n){cancelDrawing();showMessage(`All ${n} domains are drawn. Drag a corner handle on any domain to resize it. Use Clear All Domains to redraw.`);}else{showMessage(`d${pad(i)} complete. Now draw d${pad(i+1)} inside it.`);map.getContainer().style.cursor='crosshair';map.dragging.disable();}}
map.on('mousedown',pointerDown);map.on('mousemove',pointerMove);map.on('mouseup',pointerUp);map.on('touchstart',pointerDown);map.on('touchmove',pointerMove);map.on('touchend',pointerUp);
function updateProjectionUI(){const p=document.getElementById('projectionInput').value;document.getElementById('lambertOptions').classList.toggle('d-none',p!=='lambert');document.getElementById('polarOptions').classList.toggle('d-none',p!=='polar');const projected=p!=='lat-lon';document.getElementById('dxUnit').textContent=projected?'(m)':'(°)';document.getElementById('dyUnit').textContent=projected?'(m)':'(°)';const dx=document.getElementById('dxInput'),dy=document.getElementById('dyInput');dx.min=projected?'100':'0.001';dy.min=projected?'100':'0.001';dx.step=projected?'100':'0.001';dy.step=projected?'100':'0.001';updateOutputFromDomains();}
function updateOutputFromDomains(){const out=document.getElementById('output');if(!domains.length){out.innerHTML='<p class="text-muted mb-0">Set your configuration and draw d01 to begin.</p>';return;}try{const{dx,dy}=spacing(),s=settings(),rs=ratios(),v=WRF.validate(domains,dx,dy,rs,s);let cdx=dx,cdy=dy,total=0;const rows=domains.map((d,i)=>{if(i){cdx/=rs[i];cdy/=rs[i];}const raw=WRF.gridDimensions(d.getBounds(),cdx,cdy,s),ew=i?WRF.snapDimension(raw.e_we,rs[i]):raw.e_we,es=i?WRF.snapDimension(raw.e_sn,rs[i]):raw.e_sn,points=ew*es;total+=points;const ps=i?WRF.parentStart(domains[i-1].getBounds(),d.getBounds(),WRF.gridDimensions(domains[i-1].getBounds(),cdx*rs[i],cdy*rs[i],s),{e_we:ew,e_sn:es},rs[i],s):null;return `<div class="domain-summary mb-2"><strong>d${pad(i)}</strong> — ${ew} × ${es} grid points · dx=${cdx.toFixed(s.projection==='lat-lon'?5:0)} ${s.projection==='lat-lon'?'°':'m'} · dy=${cdy.toFixed(s.projection==='lat-lon'?5:0)} ${s.projection==='lat-lon'?'°':'m'}${ps?`<br><span class="text-muted">parent start: i=${ps.i}, j=${ps.j} · ratio=${rs[i]}:1</span>`:''}<br><span class="text-muted">SW ${d.getBounds().getSouthWest().lat.toFixed(4)}, ${d.getBounds().getSouthWest().lng.toFixed(4)} · NE ${d.getBounds().getNorthEast().lat.toFixed(4)}, ${d.getBounds().getNorthEast().lng.toFixed(4)}</span></div>`;}).join('');const status=v.errors.length?`<div class="alert alert-danger py-2"><strong>Errors</strong><ul class="mb-0">${v.errors.map(esc).map(x=>`<li>${x}</li>`).join('')}</ul></div>`:'<div class="alert alert-success py-2 mb-2">Core WRF nesting checks passed.</div>';const warns=v.warnings.length?`<div class="alert alert-warning py-2"><strong>Warnings</strong><ul class="mb-0"><li>${v.warnings.map(esc).join('</li><li>')}</li></ul></div>`:'';out.innerHTML=`<h5>Domain Summary</h5>${status}${warns}${rows}<div class="small"><strong>Estimated horizontal grid points:</strong> ${total.toLocaleString()}</div><div class="small text-muted mt-1">Projection: ${esc(s.projection)} · ref: ${s.refLat.toFixed(3)}, ${s.refLon.toFixed(3)}</div>`;}catch(e){out.innerHTML=`<div class="alert alert-danger mb-0">${esc(e.message)}</div>`;}}
function exportNamelist(){if(domains.length!==Number(countEl.value)){showError(`Complete all ${countEl.value} selected domains before export.`);return;}try{const{dx,dy}=spacing(),s=settings(),rs=ratios(),v=WRF.validate(domains,dx,dy,rs,s),w=wpsSettings();if(v.errors.length)throw new Error(`Fix validation errors before export: ${v.errors.join(' ')}`);const namelist=generateNamelist(domains.map(d=>d.getBounds()),{dx,dy,ratios:rs,...s,geogDataRes:document.getElementById('geogResInput').value,...w}),blob=new Blob([namelist],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='namelist.wps';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){showError(e.message);}}
function showMessage(m){document.getElementById('output').innerHTML=`<div class="alert alert-info mb-0">${esc(m)}</div>`;}function showError(m){document.getElementById('output').innerHTML=`<div class="alert alert-danger mb-0">${esc(m)}</div>`;}
countEl.addEventListener('change',()=>{buildRatioTable();clearDomains(false);});document.getElementById('drawBtn').addEventListener('click',startDrawing);document.getElementById('clearBtn').addEventListener('click',()=>clearDomains(true));document.getElementById('exportBtn').addEventListener('click',exportNamelist);document.getElementById('projectionInput').addEventListener('change',updateProjectionUI);['autoCenterInput','dxInput','dyInput','trueLat1Input','trueLat2Input','polarLatInput','polarHemisphere','geogResInput','startDateInput','endDateInput','intervalInput','geogPathInput'].forEach(id=>document.getElementById(id).addEventListener('input',updateOutputFromDomains));document.getElementById('validateFilesBtn').addEventListener('click',runWPSOutputValidation);buildRatioTable();updateProjectionUI();